Feature
fivan18/members-only pull request #1
Opened 2020-03-05 14:06 UTC by certilremy

- [ ] Include the bcrypt-ruby gem in your Gemfile
- [ ] Add the #has_secure_password method to your User file.
- [ ] create a sessions_controller.rb and the corresponding routes. Make “sign-in” links in the 
       layout as necessary.
- [ ] Set your current user whenever a user signs in.
- [ ] Build sign out functionality in your SessionsController#delete
- [ ] make sure only signed-in users can see the author of each post.
- [ ] only users who are signed in can create a post.

2020-03-05 19:45 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello, 

Thank you for that simplest result. The project is working.
However, there are some requirements that are not met

1. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/bcrypt_requirement.png), The application uses the bcrypt gem for authentication but you didn't use it in your `User` model.

2. It was asked  A `:remember_token` column to be added to the model through a migration (take a look in that [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/remember_token_requirement.png)), but there is no `remember_token`

3. a #before_create callback that generates a :remember_token which is asked [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_create_requirement.png) it 's not present

4. Please, forgot the usage of `session` in this project. The authentication should be handled only and only using `cookies`. As mentioned [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_method_requirement.png), your `log_in / sign in` method should hash the remember token into `cookies.permanent`

The remember_me token the project describes consists of storing a hash in a cookie and using it to determine in a user is logged in. Do not confuse it with the Remember me [ ] checkbox that many websites show. That is a more complex solution, which is not required here

5. As specified [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/current_user_requirement.png), It uses the `#current_user=(user)` method to set user

5. Read the comments below.

Kindly make the changes and submit a new code review request.
Thanks

Mael FOSSO

2020-03-05 19:45 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +  end
Change it to use `cookies.permanent`

2020-03-05 19:45 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +    session.clear
cookies, please.

2020-03-05 22:31 UTC, certilremy commented
> 1. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/bcrypt_requirement.png), The application uses the bcrypt gem for authentication but you didn't use it in your `User` model.

Rep. Thank you for your feedback, We will do the change about cookies. One last thing you said that we do not use bcrypt for our authentication. We didn't use it as you expected but we use it. Look at the session controller and the create method. if you want to verify,  fire up the console create a new user . You'll see your password is encrypted. There are various ways u can use bcrypt to encrypt password. We hate plagiarism this is why we come up with our own implementation method. But if you want us to copy code from the tutorial and past it to the project it fine We will remove our implementation.

2020-03-06 12:56 UTC, Torres-ssf approved these changes
### Project Approved :clap: :tada: 
Hi team :smile: 
Good work implementing the requested changes :1st_place_medal: 
**I'm approving this PR.** :smiley: 
Good luck with the next project :+1: 

Happy coding :computer: 
**Sergio Torres**

2020-03-06 14:13 UTC, merged